#! /bin/sh

pkill slstatus &

xrdb -l $HOME/.Xresources &

# wallpaper
nitrogen --restore &

# launch compton
al-compositor --start &

# restore wallpaper
nitrogen --restore &

# gnome polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# panel
al-tint2-session &
sleep 1; $HOME/.config/polybar/scripts/launch.sh &

# key bindings
sxhkd &

 

# set monitors  
if [[ $(hostname) == 'myhost' ]]; then
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
elif [[ $(hostname) == 'otherhost' ]]; then
    bspc monitor VGA-0 -d I II III IV V
    bspc monitor VGA-1 -d VI VII VIII IX X
elif [[ $(hostname) == 'yetanotherhost' ]]; then
    bspc monitor DVI-I-3 -d VI VII VIII IX X
    bspc monitor DVI-I-2 -d I II III IV V
fi



bspc config border_width    3
bspc config window_gap      0
bspc config top_padding     18
bspc config right_padding   0
bspc config bottom_padding  0
bspc config left_padding    0

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

bspc config pointer_modifier  mod1
bspc config click_to_focus    true
bspc configpointer_action1    move
bspc config pointer_action2   resize_side
bspc config pointer_action3   resize_corner

bspc rule -a Galculator state=floating
bspc rule -a Void_Exit_Session state=floating layer=above
bspc rule -a Exit_Session state=floating layer=above
