# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1505610285);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1505610405);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1505609925);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1505610165);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1505610645);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1505610045);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1505610765);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1505610525);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.bookmarks.showMobileBookmarks", false);
user_pref("browser.cache.disk.capacity", 81920);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1505604183);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.migration.version", 47);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.shieldstudy.enabled", false);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1505609928376");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1505611687376");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1505609934528");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1505613534528");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170826053331");
user_pref("browser.slowStartup.averageTime", 2473);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "file:///home/liveuser/.ArchLabs-homepage/index.html");
user_pref("browser.startup.homepage_override.buildID", "20170826053331");
user_pref("browser.startup.homepage_override.mstone", "55.0.3");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20170916);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1505604186720");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("dom.ipc.processCount.web", 4);
user_pref("e10s.rollout.cohort", "multiBucket4");
user_pref("e10s.rollout.cohortSample", "0.970310");
user_pref("e10s.rollout.cohortSample.multi", "0.438134");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 21);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.e10sMultiBlockedByAddons", false);
user_pref("extensions.getAddons.cache.lastUpdate", 1505610286);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20170302.01");
user_pref("extensions.lastAppVersion", "55.0.3");
user_pref("extensions.lastPlatformVersion", "55.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.api_url", "https://normandy.cdn.mozilla.net/api/v1");
user_pref("extensions.shield-recipe-client.dev_mode", false);
user_pref("extensions.shield-recipe-client.enabled", true);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.logging.level", 50);
user_pref("extensions.shield-recipe-client.run_interval_seconds", 86400);
user_pref("extensions.shield-recipe-client.startup_delay_seconds", 300);
user_pref("extensions.shield-recipe-client.user_id", "6143f56e-2ce2-4c98-921f-78140d52e310");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{0a875754-06dc-4092-996a-d52a01f5e6a7}\",\"addons\":{\"clicktoplay-rollout@mozilla.org\":{\"version\":\"1.3\"},\"e10srollout@mozilla.org\":{\"version\":\"2.05\"},\"followonsearch@mozilla.com\":{\"version\":\"0.9.3\"},\"onboarding@mozilla.org\":{\"version\":\"0.1\"},\"screenshots@mozilla.org\":{\"version\":\"10.12.0\"}}}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1505610102);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1505604185);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170826053331");
user_pref("media.gmp-manager.lastCheck", 1505604185);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1505610102);
user_pref("places.history.expiration.transient_current_max_pages", 191);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugins.ctprollout.cohort", "excluded");
user_pref("plugins.ctprollout.cohortSample", "0.739225");
user_pref("services.blocklist.clock_skew_seconds", 9690);
user_pref("services.blocklist.last_update_seconds", 1505600715);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1505610102);
user_pref("toolkit.startup.last_success", 1505611126);
user_pref("toolkit.telemetry.cachedClientID", "2ad5aab4-ccc2-49e6-8968-1940a7cb3ccd");
user_pref("toolkit.telemetry.previousBuildID", "20170826053331");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
